const eventsStore = [
    {
        title: "All Nations - Manhattan Missions Church Bible Study",
        description: "Manhattan Bible Study Meetup Group",
        date: new Date(2024, 2, 14, 11),
        image: "picture/pic/page2/1.jpg",
        type: "offline",
        attendees: null,
        category: "Hobbies and Passions",
        distance: 5,
    },
    {
        title: "INFJ Personality Type - Coffee Shop Meet & Greet",
        description: "Being an INFJ",
        date: new Date(2024, 2, 23, 15),
        image: "picture/pic/page2/2.jpg",
        type: "offline",
        attendees: 99,
        category: "Hobbies and Passions",
        distance: 25,
    },
    {
        title: "NYC AI Users - AI Tech Talks, Demo & Social: RAG Search and Customer Experience",
        description: "New York AI Users",
        date: new Date(2024, 2, 23, 11, 30),
        image: "picture/pic/page2/3.jpg",
        type: "offline",
        attendees: 43,
        category: "Technology",
        distance: 40,
    },
    {
        title: "Book 40+ Appointments Per Month Using AI and Automation",
        description: "New Jersey Business Network",
        date: new Date(2024, 2, 16, 14),
        image: "picture/pic/page2/4.jpg",
        type: "online",
        attendees: null,
        category: "Technology",
        distance: 10,
    },
    {
        title: "Dump writing group weekly meetup",
        description: "Dump writing group",
        date: new Date(2024, 2, 13, 11),
        image: "picture/pic/page2/5.jpg",
        type: "online",
        attendees: 77,
        category: "Hobbies and Passions",
        distance: 100,
    },
    {
        title: "Over 40s, 50s, & 60s Senior Singles Chat, Meet & Dating Community",
        description: "Over 40s, 50s, 60s Singles Chat, Meet & Dating Community",
        date: new Date(2024, 2, 14, 11),
        image: "picture/pic/page2/6.jpg",
        type: "online",
        attendees: 140,
        category: "Hobbies and Passions",
        distance: 75,
    },
];